image: docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind
    command: ["dockerd", "--host=tcp://0.0.0.0:2375"]
    alias: 'docker'

build:
  stage: build
  only:
    refs:
    - tags
  script:
    - docker version
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin $DOCKER_REGISTRY
    - docker buildx create --use
    - docker buildx build --push --provenance false --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag $DOCKER_REGISTRY/$IMAGE:$CI_COMMIT_TAG ./
