version: '3.1'

networks:
  writeup:
    external: false

services:
  mongo:
    image: mongo
    restart: unless-stopped
    networks:
      - writeup
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  writeUpBackend:
    build:
      context: ./
      dockerfile: ./backend.Dockerfile
    image: writeup-backend
    restart: unless-stopped
    networks:
      - writeup
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      #API_PORT: 8080
      DB_URI: mongo
      DB_PORT: 27017
      DB_USER: root
      DB_PASSWD: example
      #PASSWD_SECRET: randomcharacters
      #JWT_SECRET: secret
      #SHARE_SECRET: otherSecret

  writeUpFrontend:
    build:
      context: ./client
      dockerfile: ./frontend.Dockerfile
    image: writeup-frontend
    restart: unless-stopped
    networks:
      - writeup
    depends_on:
      - writeUpBackend
    ports:
      - "3000:3000"
    environment:
      API_URL: "http://localhost:8080/api/"
      #PORT: 3000

