refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h([{l}]):<7.15} {t} - {m}{n}"

  file:
    kind: rolling_file
    path: "logs/writeup.log"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 5mb
      roller:
        kind: fixed_window
        base: 0
        count: 3
        pattern: "logs/writeup.log.old.{}"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h([{l}]):<7.15} {t} - {m}{n}"

root:
  level: info
  appenders:
    - file

loggers:
  writeUp:
    level: debug
    appenders:
      - stdout
  writeup::actix:
    level: info
    appenders:
      - stdout
  actix_server: # to silence actix unless something goes wrong
    level: warn
